---
title: "Workshop4"
output: html_document
date: "2026-07-11"
---

## ASSEMBLY

make wd flye2
```bash
mkdir flye2
```

symbolic link to bbd data
```bash
ln -s /pvol/data/metagenome_assembly/bbd_0.1.fastq.gz .
```

save script and submit slurm 
```bash
sbatch run_flye_bbd.sh
```

Look at slurm as running
```bash
tail -f slurm-427.out
```

## BINNING

make metabat2 wd
```bash 
mkdir metebat2
```

extract info
```bash
 cat ../flye2/bbd/assembly_info.txt  | grep -v '#' | awk '{OFS="\t";print $1,$3}' > depths_bbd.txt
```

reorder contigs on depth
```bash
cat depths_bbd.txt | awk '{print $1}' | xargs samtools faidx ../flye2/bbd/assembly.fasta > assembly_bbd_ordered.fasta
```

run metabat 
```bash
metabat2 -i assembly_bbd_ordered.fasta -a depths_bbd.txt --cvExt -o bins_bbd/metabat --seed 5
```

## CHECK BIN QUALITY

make checkm2 wd
```bash 
mkdir checkm2
```

sort contigs shortest to longest
```bash
cat ../flye2/bbd/assembly.fasta | bioawk -c fastx '{print length($seq),$name}' | sort -n
```

make bins_bbd wd in checkm
```bash
mkdir bins_bbd 
```

copy bins from metabat2 into bin_bbd
```bash
cp ../metabat2/bins_bbd/*.fa bins_bbd/
```

put longest contig (111) into bin_bbd
```bash
samtools faidx ../flye2/bbd/assembly.fasta contig_111 > bins_bbd/contig_111.fa
```

save script and run slurm  
```bash
sbatch run_checkm_bbd.sh
```

watch slurm as running
```bash
tail -f slurm-439.out
```

## SELECT BINS

bins with a completeness (column 13) greater than 15%
```bash
cat checkm_results_bbd.txt | awk '$13>15'
```

just bin id for completeness >15%
```bash
cat checkm_results_bbd.txt | awk '$13>15{print $1}'
```

make this an output file
```bash
cat checkm_results_bbd.txt | awk '$13>15{print $1}' > bbd_topbins.txt
```

## TAXONOMIC CLASSIFICATION

make gtdbtk wd
```bash 
mkdir gtdbtk
```

make genomes wd within gtdbtk
```bash
mkdir genomes
```

copy topbin files into genomes (added contig_111 manually)
```bash 
while read bin;do echo $bin;done < ../checkm2/bbd_topbins.txt

while read bin;do echo "../metabat2/bins_bbd/${bin}.fa";done < ../checkm2/bbd_topbins.txt

while read bin;do cp "../metabat2/bins_bbd/${bin}.fa" genomes;done < ../checkm2/bbd_topbins.txt
```

save script and submit slurm 
```bash
sbatch run_gtdbtk.sh
```

watch slurm as running
```bash
tail -f slurm-561.out
```

```{r}
gtdbtk_result <- read_tsv("gtdbtk/out/gtdbtk.summary.tsv")
```


## FIND AND ANNOTATE GENES

make prokka wd
```bash
mkdir prokka
```

id first bin 
```bash
head -n 1 ../checkm2/bbd_topbins.txt
```

run prokka
```bash
bin=contig_111
prokka --outdir $bin --prefix $bin  ../metabat2/bins_bbd/contig_111.fa
```

save script and submit slurm
```bash
sbatch run_prokka.sh
```

watch slurm as running
```bash
tail -f slurm-577.out
``` 

## INFER METABOLIC PATHWAYS

```bash
mkdir minpath 
```

look at tsv for contig_111
```bash
head ../prokka/contig_111/contig_111.tsv
```

look at unique ID and EC number for each gene
```bash
head ../prokka/contig_111/contig_111.tsv | awk -F '\t' '{print $1,$5}'
```

filter for lines with EC number
```bash
head ../prokka/contig_111/contig_111.tsv | awk -F '\t' '$5{print $1,$5}'
```

remove header line 
```bash
head ../prokka/contig_111/contig_111.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'
```

include all genes
```bash
cat ../prokka/contig_111/contig_111.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'
```

send to output file
```bash
cat ../prokka/contig_111/contig_111.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus' > contig_111.ec
```

run minpath
```bash
minpath -ec contig_111.ec -report contig_111.ec.report -details contig_111.ec.details
```

look at result
```bash
head contig_111.ec.report 
```

prepare minpath inputs for all bins
```bash
while read bin;do 
  cat ../prokka/$bin/${bin}.tsv | awk -F '\t' '$5{printf("%s\t%s\n", $1,$5)}' | grep -v '^locus' > ${bin}.ec 
done < ../checkm2/bbd_topbins.txt
```

run minpath on every bin
```bash
while read bin;do 
  minpath -ec ${bin}.ec -report ${bin}.ec.report -details ${bin}.ec.details
done < ../checkm2/bbd_topbins.txt
```

# Photosynthesis pathway 

identify photosynthesis pathway
```bash
grep 'PWY-101' *.ec.report
```

contig_111.ec.report:path PWY-101 any n/a  naive 1  minpath 0  fam0  4  fam-found  1  name  photosynthesis light reactions
metabat.31.ec.report:path PWY-101 any n/a  naive 1  minpath 1  fam0  4  fam-found  4  name  photosynthesis light reactions
metabat.40.ec.report:path PWY-101 any n/a  naive 1  minpath 1  fam0  4  fam-found  1  name  photosynthesis light reactions
metabat.54.ec.report:path PWY-101 any n/a  naive 1  minpath 1  fam0  4  fam-found  1  name  photosynthesis light reactions
metabat.64.ec.report:path PWY-101 any n/a  naive 1  minpath 0  fam0  4  fam-found  1  name  photosynthesis light reactions

How many bins contain at least one gene from this pathway?
5 bins contain at least one

Which bin has all of the genes (ie a complete pathway)?
only bin metabat.31 contains all

see the taxonomy in the bins containing photosynthetic pathway
```bash
grep 'contig_111' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
```

```bash
grep 'metabat.31' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
```
metabat.31 has all genes and has Roseofilum spp. 

```bash
grep 'metabat.40' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
```

```bash
grep 'metabat.54' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
```

```bash
grep 'metabat.64' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
```

# Tetrathionate Pathway

identify tetrathionate reduction pathway
```bash
grep 'PWY-5360' *.ec.report
```

metabat.35.ec.report:path PWY-5360 any n/a  naive 1  minpath 0  fam0  3  fam-found  1  name  superpathway of tetrathionate reduction (Salmonella typhimurium)

See the taxonomy for bin containing tetrathionate pathway
```bash
grep 'metabat.35' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
```

How many bins contain the pathway PWY-5360?
only one metabat.35

What family (in a taxonomic sense) do these bins belong to?
Arcobacteraceae
